# Video parameters
videoFolder: "./test"
videoFilename: "0.mp4"
frameRate: 100
recTimeInSec: 30

# Camera parameters
cameraMake: "basler"
cameraSettings: "./campy/cameras/basler/rgb24.pfs"
pixelFormatInput: "rgb24"
pixelFormatOutput: "rgb0"
frameWidth: 1152
frameHeight: 1024

# Compression parameters
ffmpegLogLevel: "quiet"               # "quiet", "warning", "info"
gpuID: 0                              
gpuMake: "nvidia"                     # "nvidia", "amd", "intel"                  
codec: "h264"                         # "h264", "h265", or user-defined video codec
quality: 21                           # 0-55

# Display parameters
chunkLengthInSec: 5
displayFrameRate: 10

# Trigger parameters
startArduino: True
serialPort: "COM3"
digitalPins: [0,1]
